# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/ClockController/ClockController.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClockController || ORIG_REF_NAME==ClockController} -quiet] -quiet

# IP: ip/initialFrame/initialFrame.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==initialFrame || ORIG_REF_NAME==initialFrame} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: ip/frameBuffer/frameBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frameBuffer || ORIG_REF_NAME==frameBuffer} -quiet] -quiet

# IP: ip/oddr_xCLK/oddr_xCLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==oddr_xCLK || ORIG_REF_NAME==oddr_xCLK} -quiet] -quiet

# IP: ip/divider/divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider} -quiet] -quiet

# IP: ip/map_divider/map_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==map_divider || ORIG_REF_NAME==map_divider} -quiet] -quiet
