# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.cache/wt [current_project]
set_property parent.project_path D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/I2C_Controller2.v
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/ov7670_init.v
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/I2C_OV7670_RGB565_Config2.v
}
read_vhdl -library xil_defaultlib {
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/CameraDataCapture.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/DebouncedReset.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/VGA.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/VGAController.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/imports/new/button_to_pos.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/calibrateServo.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/locationMapper.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/imports/new/servo.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/TopModule.vhd
  D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/new/BrightestPoint.vhd
}
read_ip -quiet D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/ClockController/ClockController.xci
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/ClockController/ClockController_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/ClockController/ClockController.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/ClockController/ClockController_late.xdc]
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/ClockController/ClockController_ooc.xdc]

read_ip -quiet D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/initialFrame/initialFrame.xci
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/initialFrame/initialFrame_ooc.xdc]

read_ip -quiet D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]

read_ip -quiet D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/frameBuffer/frameBuffer.xci
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/frameBuffer/frameBuffer_ooc.xdc]

read_ip -quiet D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/oddr_xCLK/oddr_xCLK.xci

read_ip -quiet D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/divider/divider.xci
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/divider/divider_ooc.xdc]

read_ip -quiet D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/map_divider/map_divider.xci
set_property used_in_implementation false [get_files -all d:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/sources_1/ip/map_divider/map_divider_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/Desktop/EE102/Project/VHDL/FinalProject/FinalProject.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TopModule -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopModule.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
